<?php

namespace ContainerLxh7N7z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityRadioButtonTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\EntityRadioButtonType' shared autowired service.
     *
     * @return \App\Form\Type\EntityRadioButtonType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Core/Type/ChoiceType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/EntityRadioButtonType.php';

        return $container->privates['App\\Form\\Type\\EntityRadioButtonType'] = new \App\Form\Type\EntityRadioButtonType();
    }
}
